//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoVatChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoSoVatChat()
        {
            this.Nhas = new HashSet<Nha>();
        }
    
        public int maCoSoVatChat { get; set; }
        public Nullable<bool> baiDauXe { get; set; }
        public Nullable<bool> banCong { get; set; }
        public Nullable<bool> baoVe { get; set; }
        public Nullable<bool> cctv { get; set; }
        public Nullable<bool> dieuHoa { get; set; }
        public Nullable<bool> gacLung { get; set; }
        public Nullable<bool> sanThuong { get; set; }
        public Nullable<bool> hoBoi { get; set; }
        public Nullable<bool> mayGiat { get; set; }
        public Nullable<bool> noiThat { get; set; }
        public Nullable<bool> nuoiThuCung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nha> Nhas { get; set; }
    }
}
