//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int maNguoiDung { get; set; }
        public int maNha { get; set; }
        public Nullable<int> soSao { get; set; }
        public string noiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Nha Nha { get; set; }
    }
}
