//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int maFAQ { get; set; }
        public string cauHoi { get; set; }
        public string cauTraLoi { get; set; }
    }
}
