//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nha()
        {
            this.AnhNhas = new HashSet<AnhNha>();
            this.DanhGias = new HashSet<DanhGia>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public int maNha { get; set; }
        public int maChuNha { get; set; }
        public int maCoSoVatChat { get; set; }
        public Nullable<int> maLoaiChoThue { get; set; }
        public Nullable<int> soPhongNgu { get; set; }
        public Nullable<int> soPhongTam { get; set; }
        public Nullable<decimal> dienTich { get; set; }
        public string tinhTrang { get; set; }
        public string soNha { get; set; }
        public string phuongXa { get; set; }
        public string quanHuyen { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhNha> AnhNhas { get; set; }
        public virtual CoSoVatChat CoSoVatChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual LoaiChoThue LoaiChoThue { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
