//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int maTinNhan { get; set; }
        public int maNguoiGui { get; set; }
        public int maNguoiNhan { get; set; }
        public int loai { get; set; }
        public string noiDung { get; set; }
        public System.DateTime ngayGui { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
