//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKiemNhaTro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int maTinTuc { get; set; }
        public string tieuDe { get; set; }
        public string trichDan { get; set; }
        public string urlBao { get; set; }
        public string urlAnh { get; set; }
    }
}
